version: "3"
services:
  airia-landing-agent:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DATABASE_URI=${DATABASE_URI}
      - REDIS_URI=${REDIS_URI}
      - EVO_SERVER_URL=${EVO_SERVER_URL}
      - EVO_INSTANCE=${EVO_INSTANCE}
      - EVO_API_KEY=${EVO_API_KEY}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - OTP_TIMEOUT=${OTP_TIMEOUT}
      - OTP_COOLDOWN=${OTP_COOLDOWN}
      - JWT_SECRET=${JWT_SECRET}
    # depends_on:
    #   - redis
    #   - postgres
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airia

volumes:
  redis-data:
