version: '3'
services:
  airia-landing-agent:
    build: .
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
      - REDIS_URI=redis://redis:6379
      - EVO_SERVER_URL=https://api.evosms.com
      - EVO_INSTANCE=1
      - EVO_API_KEY=1234567890
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

volumes:
  redis-data:
