version: '3'
services:
  airia-landing-agent:
    build: .
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@postgres:5432/airia
      - REDIS_URI=redis://redis:6379
      - EVO_SERVER_URL=https://api.evosms.com
      - EVO_INSTANCE=1
      - EVO_API_KEY=1234567890
      - NODE_ENV=production
      - PORT=4000
      - OTP_TIMEOUT=300
      - OTP_COOLDOWN=30
      - JWT_SECRET=JWT_SECRET
    depends_on:
      - redis
      - postgres
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=airia

volumes:
  redis-data:
